### ISSUE TITLE
Has a question about receiver address when solana as destination chain

### ISSUE THREAD

**Issue by code-brewer** [circlefin/solana-cctp-contracts#11]
Suppose I want to bridge USDC from EVM-chain, then, upon create the ‘burn' Transaction，what destination address (solana account) should I put in? Is it normal user wallet address or ATA under that wallet address? 
If the destination account do not exist pre-hand, will solana-cctp-contract create this account automatically? If yes, this will be done at 'receive_message'  method, right? 

Of course, It would be better if your guys can provide some examples Tx url.

**Comment by chasemcdermott** [comment]
> what destination address (solana account) should I put in? Is it normal user wallet address or ATA under that wallet address?

It needs to be a hex encoded USDC token account address. Please see [this section](https://developers.circle.com/stablecoins/docs/solana-programs#mint-recipient-for-solana-as-destination-chain-transfers) in our developer docs for more information on that. Here is an example transaction transferring USDC from Ethereum to Solana: https://etherscan.io/tx/0x58158c70beab799c85c7e4c6faf8b2c453d54d85e7aee79bc35ed38d5f11cc9d

> If the destination account do not exist pre-hand, will solana-cctp-contract create this account automatically? If yes, this will be done at 'receive_message' method, right?

No, the CCTP solana contracts do not create the ATA, this would need to be done wither by the user or integrator.

**Comment by Oxwagmi** [comment]
passed hex encoded solana wallet pubkey instead of `hex encoded USDC token account address` .wasted hours to figure out this simple mistake.Thanks for explaining
